### ISSUE TITLE
Project / Kanban/ List Interface

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#10]
Create a project with Kanban.  We would like to see in the views, List which are R&D.  At this level we should also be able to search for just R&D projects.  Can we include better information of the R&D and status at this level?

**Comment by robertallanroker** [comment]
This has not been addressed.  Would like to see more on the Kanban, such as R&D Flag, # Resolved and unresolved TU's, # of running experiments.  Can we add more to UI.

**Comment by odoosocius** [comment]
![kanban](https://user-images.githubusercontent.com/31440089/31663948-45ce0020-b361-11e7-9ddf-8b776a358cad.png) Details added in Kanban view
