### ISSUE TITLE
Project Expected Resources 

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#12]
We need a list of users that are expected to contribute results on experiments.  "Expected_users", field missing.  Can we display on project screen using a multi-tagging interface.

**Comment by odoosocius** [comment]
We added expected Resources in Experiment view before
![experiment](https://user-images.githubusercontent.com/31440089/30842794-869bb202-a2a2-11e7-891b-5ed1d04fe51a.png)

Now added it to Project View with multi tagging option

![expectedresources-project](https://user-images.githubusercontent.com/31440089/30842826-a5312774-a2a2-11e7-9aec-e548ce3dc665.png)

**Comment by robertallanroker** [comment]
nice
