### ISSUE TITLE
TU needs to determine if it

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#15]
Each TU is R&D, however, it may not be SR&ED.  Hence we need to compute a SR&ED boolean value.  Hence we need additional fields/logic as follows:

- [x] Risk %, is the user given risk % they believe is associated with the individual TU.  This is needed later by project and experiments to calculate their risk.

To determine if the TU is SR&ED Eligible we must first ask the following questions for each TU (we need more fields for this)
- [x] Technology Baseline (pull-down list)
     - None 
     - Proprietary
     - Commercially available
- [x] (if not none) Does the baseline require modifications/experimentation to reduce its risk? "Experimentation Required Flag"
- [x] (Html/notes), Why is experimentation required?

Now, to determine current "SR&ED" eligibility, Risk % > 0.0% and "Requires experimentation Flag Set".

It is important to track changes and have built in collaboration on TU's hence,
- [x] Use messages with followers on each TU
- [x] Automatically assign followers to TUs based on the list of expected resources in the project record.
- [x] Each time the risk is changes within the TU, or the State changes, make sore to journalize the change in messages.

**Comment by robertallanroker** [comment]
Can we display message, perhaps with help context, but needs to say at least
"Does baseline require modifications/experimentation?"

**Comment by odoosocius** [comment]
Help Text added
