### ISSUE TITLE
TU interface

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#16]
When viewing the TU would like to see children TU's (if any) in a list below.  Make it easier to add/chil TUs and see their grouping associations.

**Comment by robertallanroker** [comment]
Would also like to see each TU have a "Short Name", 10-15 chars long, so users can have abbreviations, possibly used to multi-tagged lines used in experiments

**Comment by odoosocius** [comment]
We have provided numbered sequence for distinguish parent and child, can we use that as short name?

**Comment by robertallanroker** [comment]
Lets see for now.  may have to revist later
