### ISSUE TITLE
TU Color Coding

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#17]
In multi-tags, lists, tree's etc.  Any interface displaying the TU would like to have a standard color coding (this will slightly improve the UI) as follows:
1. "Red" Unsolved TU
2. "Green" Resolved
3. "Grey" Draft
4. "Yellow" Blocked
5. "Black" Abandoned

**Comment by robertallanroker** [comment]
I don't see this functionality.  We should the color coding in when visible on forms in lists too.

**Comment by odoosocius** [comment]
I think colors attribute is no longer supported fixed with decoration attribute
