### ISSUE TITLE
Experiment / SR&ED Eligibility

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#20]
Lets have a calculated "stored" field in each experiment that is set to true if any of the current TU's have at least one Eligible SR&ED, hence the entire Experiment is eligible for SR&ED work.

Can we include something in the interface that visually shows, that status of SR&ED eligibility.  ** Remember **.  Projects may have R&D, but SR&ED is subset of R&D work.

**Comment by robertallanroker** [comment]
I dont think we have this in the interface

**Comment by odoosocius** [comment]
dependencies added
