### ISSUE TITLE
Ghantt Chart 

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#21]
I don't see where the gantt interface shows

**Comment by muhsinalungal** [comment]
have you installed the modules 'web_gantt_view' and 'project_gantt_view'.?
sample view is attached with 
![screenshot-localhost 8080-2017-09-29-12-46-05](https://user-images.githubusercontent.com/26205626/31005083-d0749942-a514-11e7-9efe-64b3c3e69e6e.png)

**Comment by robertallanroker** [comment]
I see now.  Can we please add the two as dependencies.  The goal for the RD Module will be in this build, be a STANDALONE configurations.

**Comment by robertallanroker** [comment]
But look great!

**Comment by odoosocius** [comment]
dependencies added
