### ISSUE TITLE
Project: Functionality Issues

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#25]
Minor Interface issues:
- [x] Technical Advancements should come before Technical Uncertainties in the Tabs
- [x] Odoo v11 supports Activities within the message/mail chatter, just add activities to chatter would be nice feature.  You can see sample in v11 CRM form.
- [x] For the moment, the form display has the Activities, TA's, TU's as buttons, which at the moment seems redundant since they are already listed in the tab sections. Does it make more sense for now to remove these buttons?
- [x] Remarks field, within the TU form, we might as well use the HTML Field
Technical Advancements list on projects form, no option to edit an already existing in the list

SR&ED Eligibility:
* Note: The SR&ED Eligibility are simply YES/NO Boolean Flags that are a calculated status.

Functionality Issues:
- [x] Technical Uncertainties must be assigned to one more Technical Advancements
- [x] The TA risk% is derived by calculating (average formulae) of all the corresponding TU's that are part of that TA.
- [x] The Project risk% is derived by once again, averaging the % from all the TA's.
SR&ED eligibility on the TA is calculated by determining that the TU risk%>0 and there is at least one SR&ED TU that is not SOLVED hence the TU's risk should be also > 0%.
- [x] Experimentation Start Date must be within the FROM/TO Project Dates.  Same logic applies when modifying the FROM/TO Project if there are already experiments with start dates and intervals applied. Some additional validation/control may be required
- [ ] The TU, TA etc buttons on the Experimentation form do not appear to count or function
Start Running button, when pressed should become Stop Running to switch back.  The Interval does not change when doing this. Hence lets create the same status used in a TU

How we record results:
I will add a new issue, this format won't work and can not produce the required reporting, hence, it will be more clear if I create a separate issue for how this should work. (Have you looked at the WIKII)?

**Comment by odoosocius** [comment]
> Technical Advancements list on projects form, no option to edit an already existing in the list
Does this mean to make the lines non editable after creation?

**Comment by odoosocius** [comment]
> Start Running button, when pressed should become Stop Running to switch back. The Interval does not change when doing this
Start running button is working as: It changes the state to open when in draft, sets a boolean field false
Stopping the experiment currently does not update systematic investigation now. Systematic investigation is currently updated only by the scheduler and interval also changes automatic.
