### ISSUE TITLE
Project // Experiment // Advance Internal

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#26]
Within the experiment form, and once the experiment is running, I would like to have a button called "Advance Interval".  When pressed, there should be a prompt "Are you sure you want to advance to the next experimentation interval?", if so, we do the advance which normally would happen by our scheduler at the end of the interval period.  This button should only be available to user with a very high security level.  

whether the user advances the interval, or it happens automatically, this is where all the chronology happens and critical to the reporting.  If this functionality is not clear, make sure to ask questions.

**Comment by odoosocius** [comment]
Experiment button is now returned, This makes experiment edit more flexible and works well and experiment tab is now hidden
