### ISSUE TITLE
Timesheet Hours Tracking

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#27]
Like the timesheet APP and the interface but it doesn't yet fit the RD or Experimentation feature.
Ideally, what we need to modify is:
- [x] User adds time in UI-FORM, if project 'is-r&d' they can multi-tag the experiments they work on for those hours.
- [x] In this case, task, seems irrelevant. So, hence will this break mobile APPs, how do we add this functionality of tagging experiments while preserving the mobile apps also?  This will be tricky.

**Comment by odoosocius** [comment]
For an R&D projectTimesheet entry view, task is hidden and its replaced by experiments and user can multi tag Experiments
