### ISSUE TITLE
TA/TU and Experimentation Relationships

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#4]
Please correct as follows:

- [x] A single project can contain many technical advancements and experiments.
- [x] Technical advancements are unique to each project and do not cross multiple projects
- [x] Technical uncertainties are also unique to each project, however, they are grouped with Technical advancements, and the can exists in more than one Advancement area.
- [x] Experiments are unique to each project and do not cross projects.
- [x] Experiments, TA, TU are only accessible from within an R&D project

**Comment by robertallanroker** [comment]
- [ ] Single Project unique TA and TUs

- [ ] TU grouping to TAs

- [ ] Unique Experiments to each Project

**Comment by odoosocius** [comment]
> Experiments, TA, TU are only accessible from within an R&D project
This means there is no need of master data entry menus for these and can be added only from Project Form View, right?
> TA, TU , Experiment are unique per project so there should be some project associated with each of these and they cannot be choosen in another project?

**Comment by robertallanroker** [comment]
This has not been done.

**Comment by odoosocius** [comment]
Please comment what is not working,seems fixed
