### ISSUE TITLE
Module organization

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#6]
- [x] Cleanup / Delete "Greenlight_project" directory as needed

 the module contains a subdirectory called "greenlight_project".  This contains the old directory and duplication of those files.  When cloning into a directory the R-D module must have its configuration in the root of that folders, otherwise the ODOO pathing will be invalid.  Most git odoo clones, copy their projects into the root folder so the can be picked up automatically by the modules list in ODOO.  Hence, the current "greenlight_project" directory is currently not needed and should be removed now that we have flattened the directory structure.  Its left still intact so you can confirm we don't loose anything.

**Comment by odoosocius** [comment]
Modules are organized and uploaded to rd-tool repository.
