### ISSUE TITLE
Experimentation Start and End Dates

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#8]
Experimentation in this version is fixed to weekly intervals that start and increment to the next automatically.  Modify the start end dates could have significant impact on the chronology being recorded in activities and results.  Hence, to be safe for now, lets:
- [x] A start date can be specified when the project has not yet started
- [x] Once started, and results are recorded, it can not be changed.
- [x] The end date is automatic, when the project ends.

**Comment by odoosocius** [comment]
End Date is filled automatically when close button is clicked
